version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: nestjs.dockerfile
    command: npm run start
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
